In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Cargar los datos
df = pd.read_csv('Train_data.csv')

In [ ]:
#2. Exploración de los datos

df.head()

df.columns

#df.describe()

array(['normal', 'anomaly'], dtype=object)

In [ ]:
# 3. Análisis Inicial: ¿Qué tipos de tráfico tenemos?
print("Distribución de Tráfico:")
print(df['class'].value_counts(normalize=True) * 100)

Distribución de Tráfico:
class
normal     53.385996
anomaly    46.614004
Name: proportion, dtype: float64

In [ ]:
# 4. Limpieza: Filtrar solo ataques para ver protocolos más peligrosos
ataques = df[df['class'] == 'anomaly']

ataques

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.0,1.0,0.0,0.0,anomaly
5,0,tcp,private,REJ,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.0,0.0,1.0,1.0,anomaly
6,0,tcp,private,S0,0,0,0,0,0,0,...,9,0.04,0.05,0.00,0.00,1.0,1.0,0.0,0.0,anomaly
7,0,tcp,private,S0,0,0,0,0,0,0,...,15,0.06,0.07,0.00,0.00,1.0,1.0,0.0,0.0,anomaly
8,0,tcp,remote_job,S0,0,0,0,0,0,0,...,23,0.09,0.05,0.00,0.00,1.0,1.0,0.0,0.0,anomaly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25187,0,tcp,exec,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0.00,0.0,0.0,1.0,1.0,anomaly
25188,0,tcp,ftp_data,SF,334,0,0,0,0,0,...,39,1.00,0.00,1.00,0.18,0.0,0.0,0.0,0.0,anomaly
25189,0,tcp,private,REJ,0,0,0,0,0,0,...,13,0.05,0.07,0.00,0.00,0.0,0.0,1.0,1.0,anomaly
25190,0,tcp,nnsp,S0,0,0,0,0,0,0,...,20,0.08,0.06,0.00,0.00,1.0,1.0,0.0,0.0,anomaly
25191,0,tcp,finger,S0,0,0,0,0,0,0,...,49,0.19,0.03,0.01,0.00,1.0,1.0,0.0,0.0,anomaly

In [ ]:
# 5. Agrupación: ¿Qué protocolos usan los atacantes?
protocol_stats = ataques.groupby('protocol_type')['src_bytes'].sum().reset_index()

protocol_stats

  protocol_type  src_bytes
0          icmp     536527
1           tcp  459141908
2           udp      15282

In [ ]:
# 6. Exportar para Power BI
# Creamos una columna de 'Riesgo' basada en la duración de la conexión
df['nivel_riesgo'] = df['duration'].apply(lambda x: 'Alto' if x > 1000 else 'Bajo')

df.to_csv('datos_limpios_seguridad.csv', index=False)

¡Archivo listo para Power BI!

In [12]:
#conteo por clase
df['class'].count()

#conteo filtrado por condición
df['class'][df['class'] == 'anomaly'].count()

np.int64(11743)

In [23]:
#tipo de protocolos sin duplicados
 df['protocol_type'].unique()

class            25192
protocol_type    25192
dtype: int64

In [20]:
#Exploración columnas para gráficos
df.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'class'],
      dtype='object')

In [22]:
#Verificación cantidad de casos urgentes
df[df['urgent'] != 0]

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
3173,98,tcp,telnet,SF,621,8356,0,0,1,1,...,4,0.02,0.02,0.0,0.0,0.0,0.0,0.0,0.0,anomaly